// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package tokens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[NEWLINE-1]
	_ = x[HEADING1-2]
	_ = x[HEADING2-3]
	_ = x[HEADING3-4]
	_ = x[HEADING4-5]
	_ = x[HEADING5-6]
	_ = x[HEADING6-7]
	_ = x[PARAGRAPH-8]
	_ = x[BLOCKQUOTE-9]
	_ = x[CODEBLOCK-10]
	_ = x[LIST_ITEM-11]
	_ = x[HORIZONTAL_RULE-12]
	_ = x[TEXT-13]
	_ = x[BOLD-14]
	_ = x[ITALIC-15]
	_ = x[CODE-16]
	_ = x[LINK-17]
	_ = x[IMAGE-18]
	_ = x[LEFT_PAREN-19]
	_ = x[RIGHT_PAREN-20]
	_ = x[LEFT_BRACKET-21]
	_ = x[RIGHT_BRACKET-22]
	_ = x[ASTERISK-23]
	_ = x[UNDERSCORE-24]
	_ = x[BACKTICK-25]
	_ = x[HASH-26]
	_ = x[GREATER_THAN-27]
	_ = x[HYPHEN-28]
	_ = x[PLUS-29]
	_ = x[DOT-30]
	_ = x[COLON-31]
	_ = x[SPACE-32]
	_ = x[NUMERIC-33]
	_ = x[LINK_TEXT-34]
	_ = x[LINK_DESTINATION-35]
	_ = x[LINK_TITLE-36]
}

const _TokenType_name = "EOFNEWLINEHEADING1HEADING2HEADING3HEADING4HEADING5HEADING6PARAGRAPHBLOCKQUOTECODEBLOCKLIST_ITEMHORIZONTAL_RULETEXTBOLDITALICCODELINKIMAGELEFT_PARENRIGHT_PARENLEFT_BRACKETRIGHT_BRACKETASTERISKUNDERSCOREBACKTICKHASHGREATER_THANHYPHENPLUSDOTCOLONSPACENUMERICLINK_TEXTLINK_DESTINATIONLINK_TITLE"

var _TokenType_index = [...]uint16{0, 3, 10, 18, 26, 34, 42, 50, 58, 67, 77, 86, 95, 110, 114, 118, 124, 128, 132, 137, 147, 158, 170, 183, 191, 201, 209, 213, 225, 231, 235, 238, 243, 248, 255, 264, 280, 290}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
